<?php
/**
 * @file
 * Code for the Alo Physio Practicioners feature.
 */

include_once 'alo_physio_practicioners.features.inc';

/*
 * Add css and js
 */
function alo_physio_practicioners_page_alter() {
  drupal_add_js(drupal_get_path('module', 'alo_physio_practicioners') . '/js/alo_physio_practicioners.js');
  drupal_add_css(drupal_get_path('module', 'alo_physio_practicioners') . '/css/alo_physio_practicioners.css');
  drupal_add_css(drupal_get_path('module', 'alo_physio_practicioners') . '/css/rotating-card.css');
}
