<?php
/**
 * @file
 * Code for the Alo Physio Core feature.
 */

include_once 'alo_physio_core.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function alo_physio_core_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['wide_teaser'] = array(
    'label' => t('Wide teaser'),
    'custom settings' => TRUE,
  );
}

/*
 * Add css and js
 */
function alo_physio_core_page_alter() {
  drupal_add_js(drupal_get_path('module', 'alo_physio_core') . '/js/jquery.carouFredSel-6.1.0.js');
  drupal_add_js(drupal_get_path('module', 'alo_physio_core') . '/js/alo_physio_core.js');
  //drupal_add_css(drupal_get_path('module', 'alo_physio_core') . '/css/alo_physio_core.css');
}

/**
 * Implements hook_preprocess_node().
 *
 * @param $variables
 */
function alo_physio_core_preprocess_node(&$variables) {
  // This is used to get a custom teaser template file in the format
  // node--contenttype--viewmode.tpl.php
  $variables['theme_hook_suggestions'][] = 'node__' . $variables['view_mode'];
  $variables['theme_hook_suggestions'][] = 'node__' . $variables['type'] . '__' . $variables['view_mode'];

  // Show read more.
  $variables['read_more'] = FALSE;
  if (!drupal_is_front_page()) {
  //if ($variables['type'] == 'blog') {
    switch ($variables['view_mode']) {
      case 'teaser':
      case 'wide_teaser':
        $variables['read_more'] = TRUE;
    }
  //}
  }

}

/**
 * Helper to return current category, used to filter the blog view.
 */
function alo_physio_core_get_node_category() {
  $node = menu_get_object();
  if (isset($node->field_category[$node->language][0]['tid'])) {
    return $node->field_category[$node->language][0]['tid'];
  }
}

/**
 * Helper to get a tree including children of the term.
 * @param $tid array
 */
function alo_physio_core_get_tree($tids = array()) {
  $result_tree = array();

  foreach ($tids as $tid) {
    if ($term = taxonomy_term_load($tid)) {
      $tree = taxonomy_get_tree($term->vid, $tid, 2, FALSE);
      $result_tree = array_merge($tids, array_map('_taxonomy_get_tid_from_term', $tree));
    }
  }

  return array(implode('+', $result_tree));
}
