<?php
/**
 * @file
 * Code for the Alo Phisiotherapy Banner feature.
 */

include_once 'alo_physio_banner.features.inc';

/*
 * Add css and js
 */
function alo_physio_banner_page_alter() {
  drupal_add_css(drupal_get_path('module', 'alo_physio_banner') . '/css/alo_physio_banner.css');
}

/**
 * Hide some stuff from display.
 */
function alo_physio_banner_block_view_alter(&$data, $block) {
  switch ($block->delta) {
    case 'banner-large_banner':
      $data['subject'] = NULL;
      break;
  }
}

/**
 * hook_node_preprocess_node().
 */
function alo_physio_banner_preprocess_node(&$variables) {
  if ($variables['type'] == 'banner') {
    if (isset($variables['field_url'])) {
      // Add link to banner image.
      $variables['content']['field_image'][0]['#path']['path'] = url($variables['field_url'][LANGUAGE_NONE][0]['safe_value'], array('absolute' => TRUE));
      // Add alt and title to banner image.
      $variables['content']['field_image'][0]['#item']['title'] = $variables['title'];
      $variables['content']['field_image'][0]['#item']['alt'] = $variables['title'];
    }
  }
}
