<?php
// $Id$

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 */
function drupal_demo_install() {
  // Set the default and admin themes
  variable_set("theme_default", "seven");
  variable_set("admin_theme", "rubik");
  variable_set("node_admin_theme", '1');
  theme_enable(array("seven"));

  // Disable modules.
  module_disable(array('overlay'));
  module_disable(array('toolbar'));
}
