<?php
/**
 * @file
 * Code for the Alo Physio Case studies feature.
 */

include_once 'alo_physio_case_studies.features.inc';

/**
 *  Implements hook_views_query_alter().
 */
function alo_physio_case_studies_views_query_alter(&$view, &$query) {
  if ($view->name == 'case_studies' && $view->current_display == 'teaser') {
    if ($node = menu_get_object()) {
      // Exclude current node from blog view.
      $query->add_where(1, 'node.nid', $node->nid, '!=');
    }
  }
}
